---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catenax-managed-identity-wallets-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

spec:
  rules:
    - host: {{ .Values.certificate.host }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: catenax-managed-identity-wallets
                port:
                  number: 8080
  tls:
    - hosts:
        - {{ .Values.certificate.host }}
      secretName: tls-secret